/* eslint-disable @typescript-eslint/no-floating-promises */
import 'mocha';
import * as chai from 'chai';
import chaiAsPromised from 'chai-as-promised';

// Registers the concrete logger. Without it every `@Logger` field resolves the abstract
// `Log` from log-common and the first `Log.trace()` in Orm.resolve() throws.
import '@spinajs/log';
import { DI } from '@spinajs/di';
import { Configuration } from '@spinajs/configuration';
import { NotSupported } from '@spinajs/exceptions';
import { SelectQueryBuilder, InsertQueryBuilder, SchemaQueryBuilder, TableQueryBuilder, Orm, ICompilerOutput } from '@spinajs/orm';

import { ConnectionConf, FakePostgresDriver } from './fixture.js';

const expect = chai.expect;
chai.use(chaiAsPromised);

function db() {
  return DI.get(Orm);
}

function connection() {
  return db()!.Connections.get('postgres')!;
}

function sqb() {
  return connection().Container.resolve(SelectQueryBuilder, [connection()]);
}

function iqb() {
  return connection().Container.resolve(InsertQueryBuilder, [connection()]);
}

function schqb() {
  return connection().Container.resolve(SchemaQueryBuilder, [connection()]);
}

/** Whitespace-normalized expression, so assertions read the SQL, not the join seams. */
function sql(output: ICompilerOutput) {
  return (output.expression as string).replace(/\s+/g, ' ').trim();
}

/**
 * The SQL this dialect actually drafts, compared clause by clause against what the shared
 * (MySQL-flavoured) orm-sql layer would have produced — every difference asserted here is
 * one the shared compiler gets wrong for postgres.
 */
describe('postgres SQL compilation', function () {
  this.timeout(15000);

  beforeEach(async () => {
    DI.register(ConnectionConf).as(Configuration);
    DI.register(FakePostgresDriver).as('postgres');
    await DI.resolve(Orm);
  });

  afterEach(() => {
    DI.clearCache();
  });

  describe('select', () => {
    it('quotes identifiers with double quotes', () => {
      const result = sqb().select('*').from('users').where('id', 1).toDB();

      expect(result.expression).to.equal('SELECT * FROM "users" WHERE "id" = ?');
      expect(result.bindings).to.deep.equal([1]);
    });

    it('emits LIMIT and OFFSET as separate bound clauses', () => {
      const result = sqb().select('*').from('users').take(10).skip(20).toDB();

      expect(result.expression).to.equal('SELECT * FROM "users" LIMIT ? OFFSET ?');
      expect(result.bindings).to.deep.equal([10, 20]);
    });

    it('emits a bare OFFSET - not the MySQL max-bigint LIMIT workaround postgres rejects', () => {
      const result = sqb().select('*').from('users').skip(20).toDB();

      expect(result.expression).to.equal('SELECT * FROM "users" OFFSET ?');
      expect(result.bindings).to.deep.equal([20]);
    });
  });

  describe('insert', () => {
    it('compiles a plain insert', () => {
      const result = iqb().into('users').values({ id: 1, active: true, email: 'spine@spine.pl' }).toDB();

      expect(result.expression).to.equal('INSERT INTO "users" ("id","active","email") VALUES (?,?,?)');
      expect(result.bindings).to.be.an('array').that.includes.members([1, 'spine@spine.pl']);
    });

    it('spells insert-or-ignore as ON CONFLICT DO NOTHING, not INSERT IGNORE', () => {
      const result = iqb().into('users').values({ id: 1, email: 'spine@spine.pl' }).orIgnore().toDB();

      expect(result.expression).to.equal('INSERT INTO "users" ("id","email") VALUES (?,?) ON CONFLICT DO NOTHING');
    });

    it('spells upsert as ON CONFLICT DO UPDATE with EXCLUDED references, no re-bound values', () => {
      const result = iqb()
        .into('users')
        .values([
          { id: 1, email: 'a@spine.pl' },
          { id: 2, email: 'b@spine.pl' },
        ])
        .onDuplicate('id')
        .update(['email'])
        .toDB() as ICompilerOutput;

      expect(result.expression).to.equal('INSERT INTO "users" ("id","email") VALUES (?,?),(?,?) ON CONFLICT ("id") DO UPDATE SET "email" = EXCLUDED."email" RETURNING *');
      // only the 4 inserted values - EXCLUDED needs no bindings, so no row-0 values leak
      expect(result.bindings).to.be.an('array').that.has.lengthOf(4);
    });
  });

  describe('table DDL', () => {
    function createTable(cb: (table: TableQueryBuilder) => void) {
      const result = schqb().createTable('users', cb).toDB() as unknown as ICompilerOutput[];
      return sql(result[0]);
    }

    it('renders an auto increment key as IDENTITY, not AUTO_INCREMENT', () => {
      const stmt = createTable((table) => {
        table.int('Id').notNull().primaryKey().autoIncrement();
        table.string('Name').notNull();
      });

      expect(stmt).to.equal('CREATE TABLE "users" ("Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,"Name" VARCHAR(255) NOT NULL ,PRIMARY KEY ("Id") )'.replace(/\s+/g, ' ').trim());
    });

    it('maps MySQL type names to their postgres equivalents', () => {
      const stmt = createTable((table) => {
        table.dateTime('CreatedAt');
        table.double('Ratio');
        table.json('Payload');
        table.binary('Blob', 255);
        table.tinyint('Small');
      });

      expect(stmt).to.contain('"CreatedAt" TIMESTAMP');
      expect(stmt).to.contain('"Ratio" DOUBLE PRECISION');
      expect(stmt).to.contain('"Payload" JSONB');
      expect(stmt).to.contain('"Blob" BYTEA');
      expect(stmt).to.contain('"Small" SMALLINT');
    });

    it('renders an enum as TEXT with a CHECK constraint over its members', () => {
      const stmt = createTable((table) => {
        table.enum('Status', ['created', 'done']).notNull();
      });

      expect(stmt).to.contain(`"Status" TEXT NOT NULL CHECK ("Status" IN ('created','done'))`);
    });

    it('drops UNSIGNED and CHARACTER SET, which have no postgres spelling', () => {
      const stmt = createTable((table) => {
        table.int('foo').unsigned();
        table.string('bar').charset('utf8');
      });

      expect(stmt).to.not.contain('UNSIGNED');
      expect(stmt).to.not.contain('CHARACTER SET');
    });

    it('refuses an identity on a non-integer column', () => {
      expect(() =>
        createTable((table) => {
          table.string('foo').autoIncrement();
        }),
      ).to.throw(/identity requires an integer type/);
    });
  });

  describe('alter table', () => {
    it('adds a column with ADD COLUMN and no AFTER placement', () => {
      const result = schqb()
        .alterTable('test', (table) => {
          table.int('Id2');
        })
        .toDB() as unknown as ICompilerOutput[];

      expect(result[0].expression).to.equal('ALTER TABLE "test" ADD COLUMN "Id2" INTEGER');
    });

    it('spells MODIFY as ALTER COLUMN actions, restating NOT NULL and dropping an omitted default', () => {
      const result = schqb()
        .alterTable('test', (table) => {
          table.string('Id2', 128).notNull().modify();
        })
        .toDB() as unknown as ICompilerOutput[];

      expect(result[0].expression).to.equal('ALTER TABLE "test" ALTER COLUMN "Id2" TYPE VARCHAR(128), ALTER COLUMN "Id2" SET NOT NULL, ALTER COLUMN "Id2" DROP DEFAULT');
    });

    it('renames a column with the standard RENAME COLUMN', () => {
      const result = schqb()
        .alterTable('test', (table) => {
          table.int('OldName').rename('NewName');
        })
        .toDB() as unknown as ICompilerOutput[];

      expect(result[0].expression).to.equal('ALTER TABLE "test" RENAME COLUMN "OldName" TO "NewName"');
    });
  });

  describe('database DDL', () => {
    it('compiles CREATE DATABASE with ENCODING instead of CHARACTER SET', () => {
      const result = schqb().createDatabase('appdb').charset('UTF8').toDB();

      expect(result.expression).to.equal(`CREATE DATABASE "appdb" ENCODING 'UTF8'`);
    });

    it('refuses IF NOT EXISTS - postgres has no such clause', () => {
      expect(() => schqb().createDatabase('appdb').ifNotExists().toDB()).to.throw(NotSupported);
    });

    it('compiles DROP DATABASE IF EXISTS', () => {
      const result = schqb().dropDatabase('appdb').ifExists().toDB();

      expect(result.expression).to.equal('DROP DATABASE IF EXISTS "appdb"');
    });
  });

  describe('schema probes', () => {
    it('checks table existence against information_schema with current_schema()', async () => {
      const driver = connection() as FakePostgresDriver;
      driver.executed.length = 0;

      await schqb().tableExists('users');

      expect(driver.executed[0].stmt).to.contain('information_schema.tables');
      expect(driver.executed[0].stmt).to.contain('current_schema()');
      expect(driver.executed[0].params).to.deep.equal(['users']);
    });
  });
});
